### ISSUE TITLE
What is its advantage vs existing websocket frameworks?

### ISSUE THREAD

**Issue by kabaluyot** [pkgz/websocket#10]
What are the changes ,advantages of this websocket vs current websocket frameworks

**Comment by exelban** [comment]
@kabaluyot I use this package in some projects which need to have live updates. It's just a super simple version of websockets (at least for me).

**Comment by kabaluyot** [comment]
Yes most of the packages there are low level APIs for websocket. I see that you are using gobwas/ws package
