### ISSUE TITLE
How to set websocket scheme?

### ISSUE THREAD

**Issue by kabaluyot** [pkgz/websocket#11]
I integrated it with go-chi. How are we going to set it to wss or ws scheme?

**Comment by exelban** [comment]
@kabaluyot Hi. I believe it depends on what type of http server you use. 
Did you try to run it on https?

**Comment by kabaluyot** [comment]
Yes I tried it and during upgrade with https, it is also accessible now via wss. But I can still access it with ws, how to disable it?

**Comment by exelban** [comment]
@kabaluyot hmm, I never tried this library with wss. I must to check how it can be disabled.

**Comment by exelban** [comment]
@kabaluyot did you still have this problem?
